### ISSUE TITLE
Not able to run learn command in CLI

### ISSUE THREAD

**Issue by kyle-crews** [learn-co-curriculum/translating-orm-to-ar#10]
When running the "learn" command, the following errors are returned:

1. /Users/kylecrews/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x00007fb8b01c4ad8> (NoMethodError)

2. from /Users/kylecrews/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/kylecrews/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rubygems-bundler/noexec (LoadError)

**Comment by kyle-crews** [comment]
I was prompted to upgrade to a new version of bundler ... after upgrading, running 'learn' no longer worked. Running "gem install bundler" set me back to the correct version and things work again.
